name: GitHub Actions Build
run-name: Building ConfigurationPlaceholders

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  example-job:
    runs-on: windows-latest
    name: Building ConfigurationPlaceholders
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7'
      - name: Setup NuGet
        run: dotnet nuget add source --username DaveSenn --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DaveSenn/index.json"
      - name: Nuke Build
        shell: pwsh
        run: .\build.ps1