name: GitHub Actions Build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - run: build.ps1