name: GitHub Actions Build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Nuke Build
      shell: pwsh
      run: .\build.ps1